# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Number of characters for code blocks
  code_block_line_length: 120
  # Include tables
  tables: false

# MD033/no-inline-html - Inline HTML
MD033: false # TEMPORARY: leave this until April 11 to work-around issues with pre-existing repos
