formatter: markdown table

output:
  file: README.md
  mode: inject

sort:
  enabled: true
  by: required

recursive:
  enabled: true

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
