name: Test
on:
  pull_request:
    branches-ignore:
      - main
  push:
    branches-ignore:
      - main
jobs:
  go-test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      AWS_REGION: '${{ secrets.AWS_REGION }}'
      TF_TOKEN: '${{ secrets.TF_TOKEN }}'
      BUCKET_BUILDS: '${{ secrets.BUCKET_BUILDS }}'
      GH_TOKEN: '${{ secrets.GH_TOKEN }}'
      LAMBDA_S3_KEY: '${{ secrets.LAMBDA_S3_KEY }}'
    steps:
      - name: Setup actions/checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Go FMT
        run: |
          ls -lah
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add `go fmt ./...`
          git commit -m "github action: go fmt"
          git push
        continue-on-error: true
        working-directory: main/tests
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
      - name: Terraform FMT
        run: |
          ls -lah
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add `terraform fmt -recursive`
          git commit -m "github action: terraform fmt"
          git push
        continue-on-error: true
        working-directory: main
      - name: Test Golang Code
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0
          go mod tidy
          go test -v ./...
        working-directory: main/tests